# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate proc-macro2-diagnostics

Name:           rust-proc-macro2-diagnostics
Version:        0.10.1
Release:        %autorelease
Summary:        Diagnostics for proc-macro2

# Upstream license specification: MIT/Apache-2.0
License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/proc-macro2-diagnostics
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
%{summary}}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+colors-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+colors-devel %{_description}

This package contains library source intended for building other packages which
use the "colors" feature of the "%{crate}" crate.

%files       -n %{name}+colors-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+yansi-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+yansi-devel %{_description}

This package contains library source intended for building other packages which
use the "yansi" feature of the "%{crate}" crate.

%files       -n %{name}+yansi-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
# * skip integration tests due to use of undeclared crate or module
#   diagnostic_example
%cargo_test -- --lib
%cargo_test -- --doc
%cargo_test -- --bins
%endif

%changelog
%autochangelog
